#! /bin/bash

# papyros

export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
#set -x


_papyros_mount()
{
	local device=$1
	local mnt_directory=$2
	local md_directory=$3
	local wl_directory=$4
	local opts=$6

	local opt_str="allow_other,clone_fd,exec,nosuid,default_permissions,dev"

	# $4 ... -o
	# $5 ... remount,ro / nosuid / etc

	if [[ $opts == *"remount"* ]]; then
		_papyros_unmount $mnt_directory
	fi

	if [[ $opts == *"noatime"* ]]; then
		opt_str+=",noatime"
	fi

	if [[ $opts == *"strictatime"* ]]; then
		opt_str+=",strictatime"
	fi

	if [[ $opts == *"ro"* ]]; then
		opt_str+=",ro"
	fi

	if [[ $opts == *"kernelcache"* ]]; then
		opt_str+=",kernelcache"
	fi

	if [[ $opts == *"writeback"* ]]; then
		opt_str+=",kernelcachewriteback"
	fi

	if [[ $opts == *"writelog"* ]]; then
		opt_str+=",writelog"
	fi

	if [[ $opts == *"0readbuffer"* ]]; then
		opt_str+=",0readbuffer"
	fi

	if [[ $opts == *"noforget"* ]]; then
		opt_str+=",noforget"
	fi

	#echo $opt_str

	ulimit -n 4096 > /dev/null 2>&1
	ulimit -s 16384 > /dev/null 2>&1
	ulimit -a > /dev/null 2>&1

	$HERACLES_PATH/heracles $md_directory $wl_directory daemon $mnt_directory -f -o $opt_str

	#echo $!
	#read -p "Press enter to continue"

	sleep 5

	return 0
}

_papyros_remount()
{
	local device=$1
	local mnt_directory=$2
	local md_directory=$3
	local wl_directory=$4

	fusermount -u $mnt_directory

	$HERACLES_PATH/heracles $md_directory $wl_directory $mnt_directory -f -o allow_other,clone_fd,exec,nosuid
}

_papyros_unmount()
{
	local mnt_directory=$1

	sync
	umount $mnt_directory
	sleep 5
}

_check_papyros_filesystem()
{
	local directory=$1
}

_mkfs_papyros()
{
	local device=$1
	local spare_device=$2
	local md_directory=$3
	local wl_directory=$4	

	mkdir -p $md_directory
	rm -f $md_directory/*
	mkdir -p $wl_directory
	rm -f $wl_directory/*
	$HERACLES_PATH/mkfs.heracles $md_directory $device,$spare_device 1 1
}

_papyros_is_mounted()
{
	local mnt_directory=$1

	local mount_rec=`findmnt -rncv $mnt_directory -o TARGET,FSTYPE`
	[ -n "$mount_rec" ] || return 1 # 1 = not mounted

	if [ "$mount_rec" != "$mnt_directory fuse.heracles" ]; then
		return 2 # 2 = mounted on wrong mnt
	fi

	return 0 # 0 = mounted as expected
}

_papyros_replace_device()
{
	local md_directory=$1
	local from_device_path=$2
	local to_device_path=$3

	$HERACLES_PATH/replace_device $md_directory $from_device_path $to_device_path > /dev/null 2>&1
}
